'use strict';

module.exports = [
    'VOLTAGE',
    'CURRENT',
    'POWER',
    'ACCEL',
    'ANGL_VEL',
    'MAGN',
    'LIGHT',
    'INTENSITY',
    'PROXIMITY',
    'TEMP',
    'INCLI',
    'ROT',
    'ANGL',
    'TIMESTAMP',
    'CAPACITANCE',
    'ALTVOLTAGE',
    'CCT',
    'PRESSURE',
    'HUMIDITYRELATIVE',
    'ACTIVITY',
    'STEPS',
    'ENERGY',
    'DISTANCE',
    'VELOCITY',
    'CONCENTRATION',
    'RESISTANCE',
    'PH',
    'UVINDEX',
    'ELECTRICALCONDUCTIVITY',
    'COUNT',
    'INDEX',
    'GRAVITY'
    // 'CHAN_TYPE_UNKNOWN = INT_MAX'
];
